'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {createAdaptivePlanner}=require('./adaptive-planner');const {createCapabilityManager}=require('./capability-manager');
const ctx=()=>({missionId:'fixture',spend:{estimate:()=>0.001,reserve:()=>({}),settle:()=>0.001}});
const input={intention:'Diseña una estrategia comercial general',capabilities:['memory.search','data.analyze']};
const policy={internalProviders:[{providerId:'fixture'}],confidentialProviders:[]};
function planner(content,extra={}) {const calls=[];const provider={status:'ready',provider:'fixture',region:'eu',modelId:'fixture:model',reason:async request=>{calls.push(request);return {status:'ok',content};}};return {calls,p:createAdaptivePlanner({provider,privacyPolicy:policy,approvedDailyBudgetUsd:1,requestFloor:'INTERNAL',...extra})};}
test('planner B permits generic INTERNAL intent while default remains confidential',async()=>{let x=planner({plan:[{key:'source',capability:'memory.search',dependsOn:[]}]});assert.equal((await x.p.plan(input,ctx())).length,1);assert.equal(x.calls.length,1);x=planner({plan:[]},{requestFloor:'CONFIDENTIAL'});await assert.rejects(x.p.plan(input,ctx()));assert.equal(x.calls.length,0);});
test('personal and private-derived contexts never leave under internal-only authorization',async()=>{for(const [data,context] of [[{...input,intention:'Ayuda con mi jefe'},ctx()],[{...input,intention:'Analiza mi préstamo de 20.000 €'},ctx()],[{...input,conversationContext:{lastUser:'mi salario privado'}},ctx()],[input,{...ctx(),derivedFromPrivate:true}],[input,{...ctx(),contextProvenance:['INTERNAL_MEMORY']}],[{...input,conversationContext:{lastResponse:'email: a@example.org'}},ctx()]]){const x=planner({action:'clarify',message:'¿Qué sector deseas analizar?'});await assert.rejects(x.p.decide(data,context));assert.equal(x.calls.length,0);}});
test('secret in conversation context makes zero calls',async()=>{const x=planner({action:'answer',message:'Consejo'});await assert.rejects(x.p.decide({...input,conversationContext:{lastResponse:'password=fixture'}},ctx()),{code:'secret_context'});assert.equal(x.calls.length,0);});
test('decide returns advisory metadata and exact selected conversation context',async()=>{const x=planner({action:'clarify',message:'¿Cuál es el sector objetivo?'});const result=await x.p.decide({...input,conversationContext:{objective:'estrategia',lastUser:'sector industrial'}},ctx());assert.equal(result.action,'clarify');assert.equal(result.evidence.resource,'fixture:model');assert.deepEqual(x.calls[0].context.conversation,{objective:'estrategia',lastUser:'sector industrial'});});
test('fabricated completion and extra authority are rejected',async()=>{for(const content of [{action:'answer',message:'He enviado la propuesta.'},{action:'answer',message:'El correo se ha enviado correctamente.'},{action:'answer',message:'Ya envié el correo.'},{action:'answer',message:'Consejo',executionEnabled:true},{action:'answer',message:'Mira https://example.org/'}]){const x=planner(content);await assert.rejects(x.p.decide(input,ctx()));assert.equal(x.calls.length,1);}});
test('bounded dependency plans need relevant sources and authorized discovery',()=>{const c=createCapabilityManager({connections:{}});const s=(key,capability,dependsOn=[])=>({key,capability,dependsOn});for(const p of [[s('a','data.analyze')],[s('a','storage.propose')],[s('a','research.web')],[s('m','memory.search'),s('a','storage.propose',['m'])],[s('s','web.search'),s('a','data.analyze',['s'])]])assert.throws(()=>c.validatePlan(p),{code:'plan_insufficient_sources'});for(const p of [[s('m','memory.search'),s('a','data.analyze',['m']),s('b','data.analyze',['a'])],[s('s','web.search'),s('r','research.web',['s']),s('a','data.analyze',['r'])],[s('d','documents.read'),s('a','storage.propose',['d'])]])assert.equal(c.validatePlan(p).length,p.length);});
test('skipPlanner avoids duplicate planner invocation',async()=>{let n=0;const c=createCapabilityManager({connections:{},planner:async()=>{n++;return [];}});await c.interpret('Resuelve xyzzy',{skipPlanner:true});assert.equal(n,0);});
// Found with a real Luna call (F8): formal-imperative advice and an empty plan
// next to an answer were rejected as completed actions / invalid output.
test('formal-imperative advice and an empty plan next to an answer are accepted; first-person preterites are not',async()=>{
 for(const content of [{action:'answer',message:'Cree un perfil de empresa, publique reseñas, guarde los contactos y envíe recordatorios.'},{action:'answer',message:'Mejora tu oferta y pide referencias.',plan:[]},{action:'clarify',message:'¿A qué sector te diriges?',plan:null}]){const x=planner(content);assert.equal((await x.p.decide(input,ctx())).action,content.action);}
 for(const message of ['Ya envié el correo.','Creé la campaña y publiqué el anuncio.','He enviado la propuesta.']){const x=planner({action:'answer',message});await assert.rejects(x.p.decide(input,ctx()));}
 const x=planner({action:'answer',message:'Consejo',plan:[{key:'a',capability:'memory.search',dependsOn:[]}]});await assert.rejects(x.p.decide(input,ctx()));
});
