'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {Readable}=require('node:stream');
const {createChatGateway}=require('./chat-gateway');const {createSupervisedRuntime}=require('./mission-runtime');const {createServerComposition}=require('./server-composition');const {createAdaptivePlanner}=require('./adaptive-planner');const {createPublicResearchAdapters}=require('./resource-adapters');const {createHmacIntegrity}=require('./integrity');const {randomBytes}=require('node:crypto');
const KEY=randomBytes(32);const integrity=createHmacIntegrity({key:KEY});
const A={tenantId:'family:user-aaa',clientId:'family:user-aaa',userId:'user-aaa',roles:['owner'],status:'ACTIVE'};const B={...A,tenantId:'family:user-bbb',clientId:'family:user-bbb',userId:'user-bbb'};
const membershipProvider={findMemberships:async({authenticatedUserId})=>[A,B].filter(v=>v.userId===authenticatedUserId)};
const identity={uid:A.userId,clientId:A.clientId,role:'family_member',authorized:true};
const make=()=>createChatGateway({membershipProvider});
test('chat rejects body tenant spoofing and unauthenticated identities',async()=>{const g=make();await assert.rejects(()=>g.handle(identity,{query:'Recuerda x',tenantId:B.tenantId}),{code:'chat_request_invalid'});await assert.rejects(()=>g.handle(null,{query:'Recuerda x'}),{code:'authenticated_identity_required'});});
test('chat plain UX hides agents, JSON, traces and provider machinery',async()=>{const g=make();const s=await g.handle(identity,{query:'Recuerda cita',conversationId:'conv-0001'});assert.match(s.response,/memoria personal/);assert.equal(s.details,undefined);assert.equal(s.executionEnabled,false);});
test('chat natural follow-up resumes original mission only in owning conversation',async()=>{const g=make();const s=await g.handle(identity,{query:'Revisa correo',conversationId:'conv-0001'});assert.match(s.response,/Permiso solicitado/);const h=await g.runtime.openSession(identity.uid);g.runtime.connections.install(h,'mail',{...A,origin:'fixture',scopes:['mail.read'],read:async()=>({...A,items:[{text:'Conectado'}]})});const next=await g.handle(identity,{query:'continúa',conversationId:'conv-0001'});assert.equal(next.missionId,s.missionId);assert.equal(next.response,'Conectado');const other=await g.handle({...identity,uid:B.userId,clientId:B.clientId},{query:'continúa',conversationId:'conv-0001'});assert.notEqual(other.missionId,s.missionId);});
test('natural follow-up resumes a mission waiting for connection after the context TTL; hazlo after a blocked request grants nothing',async()=>{let clock=Date.parse('2026-10-04T10:00:00Z');const g=createChatGateway({runtime:createSupervisedRuntime({membershipProvider,now:()=>new Date(clock).toISOString()})});const s=await g.handle(identity,{query:'Revisa correo',conversationId:'conv-0002'});assert.match(s.response,/Permiso solicitado/);clock+=3*60*60*1000;const h=await g.runtime.openSession(identity.uid);g.runtime.connections.install(h,'mail',{...A,origin:'fixture',scopes:['mail.read'],read:async()=>({...A,items:[{text:'Conectado'}]})});const next=await g.handle(identity,{query:'ya lo he conectado',conversationId:'conv-0002'});assert.equal(next.missionId,s.missionId);assert.equal(next.response,'Conectado');const blocked=await g.handle(identity,{query:'Dame mi contraseña del banco',conversationId:'conv-0002'});assert.equal(blocked.outcome,'BLOCKED');const again=await g.handle(identity,{query:'Hazlo.',conversationId:'conv-0002'});assert.equal(again.outcome,'BLOCKED');assert.equal(again.missionId,null);assert.equal(again.executionEnabled,false);});
test('a long public page is cut at its last complete sentence, never mid-qualification',async()=>{const scope={tenantId:A.tenantId,clientId:A.clientId,userId:A.userId};const page='<p>'+'Frase general del servicio con contenido suficiente. '.repeat(37)+'Beta incluye soporte solo en inglés y nunca en español.</p>';const a=createPublicResearchAdapters({scope,origin:'fixture',search:async()=>[],fetcher:{fetchPage:async()=>({text:page})}});const {items}=await a.fetch.read({scope,urls:['https://example.org/x']});assert.ok(items[0].text.length<=2000);assert.match(items[0].text,/contenido suficiente\.$/);assert.doesNotMatch(items[0].text,/Beta incluye soporte/);});
test('server integration disabled by default',()=>assert.equal(createServerComposition(),null));
test('real HTTP boundary uses authenticated identity and scoped persistent memory',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'v3-http-'));try{const server=createServerComposition({enabled:true,cohortUids:'user-aaa,user-bbb',integrityKey:KEY,memoryRoot:root,authorizeIdentity:claims=>({ok:true,identity:{clientId:'family:'+claims.uid}})});async function req(body,who=identity){const request=Readable.from([JSON.stringify(body)]);request.oxkioIdentity=who;let status,data;await server.handle(request,{writeHead:s=>status=s,end:d=>data=d});return {status,data:data?JSON.parse(data):null};}assert.equal((await req({query:'Recuerda PRIVATE_A',conversationId:'conv-0001'})).status,200);const b=await req({query:'Recupera memoria',conversationId:'conv-0001'},{...identity,uid:B.userId,clientId:B.clientId});assert.ok(!JSON.stringify(b).includes('PRIVATE_A'));assert.equal((await req({query:'Recupera memoria',tenantId:A.tenantId})).status,400);assert.equal((await req({},null)).status,401);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('permission isolation: viewer cannot write memory',async()=>{const r=createSupervisedRuntime({membershipProvider:{findMemberships:async()=>[{...A,roles:['viewer']}]}});const h=await r.openSession(A.userId);await assert.rejects(()=>r.start(h,{text:'Recuerda no write',conversationId:'conv-0001'}),{code:'permission_denied'});});
const CATALOG={'openai:fixture':{provider:'openai',tier:'small_model',inputUsdPerMillion:1,outputUsdPerMillion:1,pricingVersion:'test',pricingSource:'operator-config',reviewedAt:'2026-10-03'}};
const POLICY={confidentialProviders:[{providerId:'openai',region:'eu'}]};
const reasoning=(onCall,result)=>({status:'ready',provider:'openai',region:'eu',modelId:'openai:fixture',reason:async()=>{onCall();return result;}});
test('planner unknown price / zero approved budget makes zero provider calls and falls back',async()=>{let calls=0;for(const [modelId,budget] of [['openai:unknown',1],['openai:fixture',0]]){const p=createAdaptivePlanner({provider:{...reasoning(()=>calls++,{status:'ok'}),modelId},privacyPolicy:POLICY,approvedDailyBudgetUsd:budget});const r=createSupervisedRuntime({membershipProvider,planner:p.plan,catalog:CATALOG});const h=await r.openSession(A.userId);const s=await r.start(h,{text:'Resuelve xyzzy',conversationId:'conv-0001'});assert.equal(s.outcome,'NEEDS_INFORMATION');}assert.equal(calls,0);});
test('planner uses reviewed catalog pricing, per-owner persisted ledger and bounded attempts',async()=>{let calls=0;const p=createAdaptivePlanner({approvedDailyBudgetUsd:0.03,privacyPolicy:POLICY,provider:reasoning(()=>calls++,{status:'ok',content:{plan:[{key:'source',capability:'memory.search',dependsOn:[]}]},usage:{inputTokens:10,outputTokens:10}})});const r=createSupervisedRuntime({membershipProvider,planner:p.plan,catalog:CATALOG});const a=await r.openSession(A.userId),b=await r.openSession(B.userId);const s=await r.start(a,{text:'Resuelve xyzzy',conversationId:'conv-0001'});assert.equal(s.status,'COMPLETED');assert.equal(calls,1);const day=(await r.costs(a))[0];assert.equal(day.calls,1);assert.equal(day.chargedUsd,0.00002);assert.equal(day.models['openai:fixture'].calls,1);assert.equal(day.openReservations,0);assert.deepEqual(await r.costs(b),[]);});
test('public research adapter delegates DNS/robots/redirect protection to existing fetcher',async()=>{let used;const {fetch,search}=createPublicResearchAdapters({scope:A,origin:'fixture',search:async()=>[{title:'Source',url:'https://example.org/page'}],fetcher:{fetchPage:async(url,options)=>{used=options;return {url,text:'Public text'};}}});assert.equal((await search.read({scope:A,query:'topic'})).items[0].url,'https://example.org/page');assert.equal((await fetch.read({scope:A,urls:['https://example.org/page']})).items[0].text,'Public text');assert.equal(used.allowedSite,'example.org');await assert.rejects(()=>fetch.read({scope:B,urls:['https://example.org/']}),{code:'adapter_scope_invalid'});});
test('pause in flight discards result until explicitly resumed',async()=>{const r=createSupervisedRuntime({membershipProvider});const h=await r.openSession(A.userId);let entered,release;const e=new Promise(resolve=>entered=resolve);let calls=0;r.connections.install(h,'mail',{...A,origin:'fixture',scopes:['mail.read'],read:async()=>{calls++;if(calls===1){entered();await new Promise(resolve=>release=resolve);}return {...A,items:[{text:'Read result'}]};}});const pending=r.start(h,{text:'Revisa correo',conversationId:'conv-0001'});await e;const [m]=await r.conversation(h,'conv-0001');assert.equal((await r.pause(h,m.id)).status,'PAUSED');release();assert.equal((await pending).status,'PAUSED');assert.equal((await r.resume(h,m.id)).status,'COMPLETED');});

test('scoped real ApprovalQueue handoff never shares proposal with B or enables execution',async()=>{const {createScopedApprovalFactory}=require('./approval-factory');const root=fs.mkdtempSync(path.join(os.tmpdir(),'v3-approval-'));try{const factory=createScopedApprovalFactory({root});const r=createSupervisedRuntime({membershipProvider,approvalFactory:factory});const a=await r.openSession(A.userId);r.connections.install(a,'mail',{...A,scopes:['mail.read'],origin:'fixture',read:async()=>({...A,items:[{text:'Factura PRIVATE_A'}]})});r.connections.install(a,'storage',{...A,scopes:['documents.read'],origin:'fixture',read:async()=>({...A,items:[]})});const s=await r.start(a,{text:'Organiza facturas en carpetas',conversationId:'conv-0001'});assert.equal(s.status,'NEEDS_APPROVAL');assert.ok(s.approvalId);const boundA=await factory(A),boundB=await factory(B);assert.equal((await boundA.queue.listPending()).length,1);assert.deepEqual(await boundB.queue.listPending(),[]);assert.equal(s.executionEnabled,false);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('verifier rejection cannot commit memory or a reusable workflow',async()=>{const r=createSupervisedRuntime({membershipProvider,agentOverrides:{'memory.remember':async()=>({itemIds:['invented']})}});const h=await r.openSession(A.userId);const s=await r.start(h,{text:'Recuerda UNVERIFIED',conversationId:'conv-0001'});assert.notEqual(s.status,'COMPLETED');assert.equal(s.result,null);const read=await r.start(h,{text:'Recupera memoria',conversationId:'conv-0002'});assert.equal(read.result.items.length,0);});
test('corrupted persistent file fails closed instead of resetting private memory',async()=>{const {createMemoryStoreFactory}=require('./memory-store');const root=fs.mkdtempSync(path.join(os.tmpdir(),'v3-corrupt-'));try{let r=createSupervisedRuntime({membershipProvider,storeFactory:createMemoryStoreFactory({root,integrity})});let h=await r.openSession(A.userId);await r.start(h,{text:'Recuerda PRIVATE',conversationId:'conv-0001'});const file=path.join(root,fs.readdirSync(root)[0]);fs.writeFileSync(file,'not valid JSON');r=createSupervisedRuntime({membershipProvider,storeFactory:createMemoryStoreFactory({root,integrity})});h=await r.openSession(A.userId);await assert.rejects(()=>r.start(h,{text:'Recupera memoria',conversationId:'conv-0001'}));assert.equal(fs.readFileSync(file,'utf8'),'not valid JSON');}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('learning reuses verified procedure within owner without rerunning planner',async()=>{let calls=0;const r=createSupervisedRuntime({membershipProvider,planner:async()=>{calls++;return [{key:'memory',capability:'memory.search',dependsOn:[]}];}});const a=await r.openSession(A.userId),b=await r.openSession(B.userId);await r.start(a,{text:'Consulta algo nuevo',conversationId:'conv-0001'});await r.start(a,{text:'Consulta algo nuevo',conversationId:'conv-0002'});assert.equal(calls,1);await r.start(b,{text:'Consulta algo nuevo',conversationId:'conv-0001'});assert.equal(calls,2);});

test('planner cannot authorize a memory write not requested by the human',async()=>{const r=createSupervisedRuntime({membershipProvider,planner:async()=>[{key:'remember',capability:'memory.remember',dependsOn:[]}]});const h=await r.openSession(A.userId);const s=await r.start(h,{text:'Valora opciones',conversationId:'conv-0001'});assert.equal(s.outcome,'NEEDS_INFORMATION');assert.equal(s.id,undefined);const read=await r.start(h,{text:'Recupera memoria',conversationId:'conv-0002'});assert.equal(read.result.items.length,0);});

test('mixed-source item IDs cannot alias private mail with public discovery',async()=>{const r=createSupervisedRuntime({membershipProvider,planner:async()=>[{key:'mail',capability:'gmail.read',dependsOn:[]},{key:'search',capability:'web.search',dependsOn:[]},{key:'analysis',capability:'data.analyze',dependsOn:['mail','search']}]});const h=await r.openSession(A.userId);r.connections.install(h,'mail',{...A,scopes:['mail.read'],origin:'fixture',read:async()=>({...A,items:[{text:'PRIVATE_MAIL'}]})});r.connections.install(h,'search',{...A,scopes:['public.search'],origin:'fixture',read:async()=>({...A,items:[{text:'Public search',url:'https://example.org/'}]})});const s=await r.start(h,{text:'Consulta fuentes',conversationId:'conv-0001'});assert.equal(s.status,'COMPLETED');assert.equal(new Set(s.result.items.map(v=>v.id)).size,2);assert.equal(s.result.items.find(v=>v.text==='PRIVATE_MAIL').provenance,'GMAIL');});
